[package]
name = "vers"
version = "0.0.17"
authors = ["ink8bit <ink8bit@users.noreply.github.com>"]
edition = "2018"

publish = false
description = "CLI utility to change package version in JavaScript projects"

[dependencies]
clap = "3.0.0-beta.2"
chrono = "0.4.19"
terminal-spinners = "0.3.1"
colored = "2.0.0"
reqwest = { version = "0.11.4", features = ["json"] }
tokio = { version = "1.7.1", features = ["full"] }

[lib]
name = "vers"
path = "src/lib.rs"
