[package]
name = "vers"
version = "0.0.13"
authors = ["ink8bit <ink8bit@users.noreply.github.com>"]
edition = "2018"

publish = false
description = "CLI utility to change package version in JavaScript projects"

[dependencies]
clap = "3.0.0-beta.2"
chrono = "0.4.19"

[lib]
name = "vers"
path = "src/lib.rs"
