[package]
name = "vers"
version = "0.0.17"
authors = ["ink8bit <ink8bit@users.noreply.github.com>"]
edition = "2018"

publish = false
description = "CLI utility to change package version in JavaScript projects"

[dependencies]
clap = "3.0.4"
chrono = "0.4.19"
terminal-spinners = "0.3.2"
colored = "2.0.0"

[lib]
name = "vers"
path = "src/lib.rs"
