[package]
name = "vers"
version = "0.1.0"
authors = ["ink8bit <ink8bit@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
serde = "1.0.92"
serde_json = "1.0.39"
serde_derive = "1.0.92"
