[package]
name = "vers"
version = "0.1.0"
authors = ["ink8bit <ink8bit@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.53"
serde = { version = "1.0.111", features = ["derive"] }
